name: Extrair Emissões 2024

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install pandas
          pip install openpyxl
          pip install requests

      - name: Rodar script
        run: python -u extrair_emissoes_2024.py

      - name: Upload do resultado
        uses: actions/upload-artifact@v4
        with:
          name: emissoes-2024
          path: emissoes_2024.csv
